[tool.poetry]
description = ""
authors = []
readme = "README.md"
packages = [{ include = "python3" }]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
